Repository AY2122S2-CS2103T-T13-4/tp, pull requests merged in 2022-04, with the labels that each got.

#195 Fix archive undo branch
  docs/UserGuide.md
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/images/ModelClassDiagram.png
  docs/images/StorageClassDiagram.png
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddModuleCommand.java
  src/main/java/seedu/address/logic/commands/ArchiveCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/ClearModulesCommand.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/CommentCommand.java
  src/main/java/seedu/address/logic/commands/CopyCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DeleteModuleCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/RedoableCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/commands/StackUndoRedo.java
  src/main/java/seedu/address/logic/commands/StatusCommand.java
  src/main/java/seedu/address/logic/commands/SwitchCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/module/Module.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/ui/AddWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/AddWindow.fxml
  src/main/resources/view/EditWindow.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearModulesCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/commands/StatusCommandTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
Labels: type.Bug

#198 Fix PED Bugs
  docs/UserGuide.md
  src/main/java/seedu/address/model/module/Module.java
Labels: type.UserGuide, type.Documentation

#204 Draft PPP
  docs/team/fantablack.md
Labels: type.Documentation

#215 Update responsibility in AboutUs.md
  docs/AboutUs.md
Labels: type.Documentation

#221 Update DG
  docs/DeveloperGuide.md
Labels: type.DeveloperGuide, type.Documentation

#218 Doc and code cleanup
  docs/DeveloperGuide.md
  docs/diagrams/UndoRedo0.puml
  docs/diagrams/UndoRedo1.puml
  docs/diagrams/UndoRedo2.puml
  docs/diagrams/UndoRedo3.puml
  docs/diagrams/UndoRedo4.puml
  docs/diagrams/UndoRedo5.puml
  docs/diagrams/UndoRedo6.puml
  docs/diagrams/UndoRedo7.puml
  docs/diagrams/UndoRedoState0.puml
  docs/diagrams/UndoRedoState1.puml
  docs/diagrams/UndoRedoState2.puml
  docs/diagrams/UndoRedoState3.puml
  docs/diagrams/UndoRedoState4.puml
  docs/diagrams/UndoRedoState5.puml
  docs/diagrams/UndoSequenceDiagram.puml
  docs/images/UndoRedo0.png
  docs/images/UndoRedo1.png
  docs/images/UndoRedo2.png
  docs/images/UndoRedo3.png
  docs/images/UndoRedo4.png
  docs/images/UndoRedo5.png
  docs/images/UndoRedo6.png
  docs/images/UndoRedo7.png
  docs/images/UndoRedoState0.png
  docs/images/UndoRedoState1.png
  docs/images/UndoRedoState2.png
  docs/images/UndoRedoState3.png
  docs/images/UndoRedoState4.png
  docs/images/UndoRedoState5.png
  docs/images/UndoSequenceDiagram.png
  docs/team/junlee1991.md
  src/main/java/seedu/address/logic/commands/StackUndoRedo.java
Labels: documentation, type.Documentation
