Repository AY2122S2-CS2103T-T13-4/tp, pull requests merged in 2022-03, with the labels that each got.

#34 Update project name in fantablack PPP
  docs/team/fantablack.md
Labels: type.Documentation

#37 Update Missing parts of DeveloperGuide.md
  docs/DeveloperGuide.md
Labels: type.DeveloperGuide

#42 Update DG - add use case for existing features
  docs/DeveloperGuide.md
Labels: type.DeveloperGuide, type.Documentation

#41 Change example output and better error handling
  src/main/java/seedu/address/logic/commands/StatusCommand.java
  src/main/java/seedu/address/logic/parser/StatusCommandParser.java
Labels: type.Bug, priority.MEDIUM

#46 Implement GUI for adding persons into ModuleMate Finder
  src/main/java/seedu/address/ui/AddWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/AddWindow.css
  src/main/resources/view/AddWindow.fxml
  src/main/resources/view/MainWindow.fxml
Labels: priority.MEDIUM, type.Feature

#47 Update Ui for PersonCard to display an Image according to Status
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/images/blacklist.png
  src/main/resources/images/favourite.png
  src/main/resources/images/placeholder.png
  src/main/resources/view/AddWindow.fxml
  src/main/resources/view/PersonListCard.fxml
Labels: priority.MEDIUM, type.Feature

#50 Implement fix for Filter command not showing error message in UI
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/commands/StatusCommand.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
Labels: priority.HIGH, type.Bug

#48 Update edit command to not allow tags to be edited
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/Prefix.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
Labels: priority.HIGH, type.Feature

#44 Add sort command to ModuleMateFinder
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/person/Status.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/PersonComparatorTest.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
Labels: priority.MEDIUM, type.Feature

#56 Update admin stuff
  docs/AboutUs.md
  docs/team/bakano98.md
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: type.Documentation

#58 Extend usage of AddCommand
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
Labels: priority.MEDIUM, type.Feature, type.Enhancement

#64 Update UG to reflect changes from v1.2
  docs/UserGuide.md
Labels: type.UserGuide, type.Documentation

#66 Sort clear test branch
  docs/UserGuide.md
  docs/team/lawwm.md
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DeleteModuleCommandParser.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/test/java/seedu/address/logic/commands/DeleteModuleCommandTest.java
  src/test/java/seedu/address/logic/commands/PersonComparatorTest.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
Labels: type.Enhancement, priority.LOW

#77 Update UG, PPP
  docs/UserGuide.md
  docs/images/addWindow.png
  docs/team/bakano98.md
Labels: type.Documentation

#72 AddWindow UX Enhancement
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/ui/AddWindow.java
  src/main/resources/view/AddWindow.css
  src/main/resources/view/AddWindow.fxml
Labels: priority.MEDIUM, type.Enhancement

#78 Copy command branch
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/CopyCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/CopyCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/Prefix.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/model/module/Module.java
  src/main/java/seedu/address/model/person/FormatPersonUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/CommandBox.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/parser/ArgumentTokenizerTest.java
Labels: type.Enhancement, priority.LOW

#83 Add COMMENT feature to ModuleMate Finder
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddModuleCommand.java
  src/main/java/seedu/address/logic/commands/ClearModulesCommand.java
  src/main/java/seedu/address/logic/commands/CommentCommand.java
  src/main/java/seedu/address/logic/commands/DeleteModuleCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/StatusCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/CommentCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Comment.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/CommentCommandTest.java
  src/test/java/seedu/address/logic/parser/CommentCommandParserTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: priority.MEDIUM, type.Feature

#84 Update DG stuff
  docs/DeveloperGuide.md
  docs/diagrams/AddSequenceDiagram.puml
  docs/diagrams/GuiAddActivityDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/AddNoParamsSequenceDiagram.png
  docs/images/GuiAddActivityDiagram.png
  docs/images/UiClassDiagram.png
  docs/team/bakano98.md
Labels: priority.HIGH, type.Documentation

#91 Update DG with Add Module implementation
  docs/DeveloperGuide.md
  docs/diagrams/AddModuleSequenceDiagram.puml
Labels: type.DeveloperGuide, type.Documentation

#92 Update DG for Btaykb
  docs/DeveloperGuide.md
  docs/diagrams/CommentSequenceDiagram.puml
  docs/images/CommentSequenceDiagram.png
Labels: type.DeveloperGuide, type.Documentation

#89 Add comment field for sort and copy
  src/main/java/seedu/address/logic/commands/CopyCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/CopyCommandParser.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/model/person/Comment.java
  src/main/java/seedu/address/model/person/FormatPersonUtil.java
Labels: type.Bug, priority.LOW

#100 Update user guide stuff
  build.gradle
  docs/UserGuide.md
  docs/images/edit_window.png
  docs/images/helpMessage.png
  docs/index.md
  docs/team/bakano98.md
  src/main/resources/images/add-contact.png
  src/main/resources/images/edit-contact.png
  src/main/resources/view/AddWindow.fxml
  src/main/resources/view/EditWindow.fxml
Labels: type.Documentation, type.Enhancement

#104 Update comment deletion
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/CommentCommand.java
  src/main/java/seedu/address/logic/parser/CommentCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Comment.java
  src/test/java/seedu/address/logic/parser/CommentCommandParserTest.java
Labels: type.Enhancement, priority.LOW

#88 Add comment field to AddWindow
  build.gradle
  src/main/java/seedu/address/ui/AddWindow.java
  src/main/resources/view/AddWindow.fxml
  src/main/resources/view/AdditionalWindows.css
Labels: priority.HIGH, type.Feature, type.Enhancement

#106 Update ug
  docs/UserGuide.md
Labels: type.UserGuide

#105 Update UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/SortSequenceDiagram.png
  docs/team/lawwm.md
Labels: documentation

#107 Update DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddModuleSequenceDiagram.puml
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/images/AddModuleSequenceDiagram.png
  docs/images/BetterModelClassDiagram.png
  docs/images/ModelClassDiagram.png
  src/main/java/seedu/address/logic/commands/StatusCommand.java
Labels: type.DeveloperGuide, type.Documentation

#102 Enhance Edit/AddWindow UX
  src/main/java/seedu/address/ui/AddWindow.java
  src/main/java/seedu/address/ui/EditWindow.java
  src/main/resources/view/EditWindow.fxml
Labels: priority.HIGH, type.Enhancement

#111 Update DG
  docs/DeveloperGuide.md
  docs/team/btaykb.md
Labels: type.DeveloperGuide, type.Documentation

#112 Update UI
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/addWindow.png
  docs/images/annotated_person.png
  docs/images/edit_window.png
  docs/images/filterExample.png
  src/main/java/seedu/address/ui/AddWindow.java
  src/main/java/seedu/address/ui/EditWindow.java
  src/main/resources/view/AddWindow.fxml
  src/main/resources/view/AdditionalWindows.css
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/EditWindow.fxml
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
Labels: type.Bug, priority.MEDIUM, type.Enhancement

#115 Fix empty table background colour
  src/main/resources/view/DarkTheme.css
Labels: type.Bug

#122 Bind F10 to SwitchCommand
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/MainWindow.fxml
Labels: priority.MEDIUM, type.Enhancement

#123 Update SwitchMenuItem and resultDisplay
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/StatusBarFooter.java
  src/main/resources/view/MainWindow.fxml
Labels: priority.MEDIUM, type.Enhancement

#124 Archive/unarchive extension
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/BookNames.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ArchiveCommand.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/CopyCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/SwitchCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ArchiveCommandParser.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/StatusBarFooter.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
Labels: priority.HIGH, type.Feature, type.Enhancement

#90 Add undo and redo command feature
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddModuleCommand.java
  src/main/java/seedu/address/logic/commands/ArchiveCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/ClearModulesCommand.java
  src/main/java/seedu/address/logic/commands/Command.java
  src/main/java/seedu/address/logic/commands/CommentCommand.java
  src/main/java/seedu/address/logic/commands/CopyCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DeleteModuleCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/RedoableCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/commands/StackUndoRedo.java
  src/main/java/seedu/address/logic/commands/StatusCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/RedoCommandTest.java
  src/test/java/seedu/address/logic/commands/UndoCommandTest.java
  src/test/java/seedu/address/logic/parser/CommandParserTestUtil.java
  src/test/java/seedu/address/logic/parser/CopyCommandParserTest.java
Labels: priority.HIGH, type.Feature

#133 Update UG
  docs/UserGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/images/BetterModelClassDiagram.png
  docs/images/ModelClassDiagram.png
Labels: type.DeveloperGuide, type.Documentation

#135 Revamped archiving logic
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddModuleCommand.java
  src/main/java/seedu/address/logic/commands/ArchiveCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/ClearModulesCommand.java
  src/main/java/seedu/address/logic/commands/CommentCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DeleteModuleCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/commands/StatusCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddModuleCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearModulesCommandTest.java
  src/test/java/seedu/address/logic/commands/CommentCommandTest.java
  src/test/java/seedu/address/logic/commands/CopyCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteModuleCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/RedoCommandTest.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/commands/StatusCommandTest.java
  src/test/java/seedu/address/logic/commands/UndoCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: priority.HIGH, type.Bug, type.Enhancement
